### ISSUE TITLE
No world news role results in bad ping

### ISSUE THREAD

**Issue by fadedmax** [Dukt-Hosting/bot-zerocords#2]
![image](https://user-images.githubusercontent.com/32599075/99751930-833ed880-2aa0-11eb-9dd5-f67ca7a63993.png)
If you look here, you can see how it pinged "None" As that is what is in the database

**Comment by sn8to** [comment]
Potentially fixed this in commit 2b8623a, waiting for testing before closing.

**Comment by SpicyTakis** [comment]
Looks good, im going to go ahead and close this.
![image](https://user-images.githubusercontent.com/67237931/102420878-1fd99500-3fd1-11eb-8640-bcadd07ae47c.png)
